services:
#    pacee_game.example:
#        class: paceeGameBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    pacee_game.GameManager:
        class: paceeGameBundle\GameManager\paceeGameManager